baseurl = "/"
title = "Sergio Navadijo"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Sergio Navadijo"
disqusShortname = "XXX"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Sergio Navadijo"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"
    


[Params]
    intro = true
    headline = "AGG STRENGTH"
    description = "Strength and conditioning for Aesthetic Group Gymnastics"
    email = "sergionavadijo@gmail.com"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "the book"
    url = "/project"
    weight = 2

[[menu.main]]
    name = "Coaching"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
