---
title: How to have fewer injuries
author: ''
date: '2018-10-04'
slug: how-to-have-fewer-injuries
categories: []
tags: []
description: ''
---
From acute and chronic low back pain to knee problems and ankle sprains, you are probably familiar with AGG injuries.

One non-solution is to take this for granted and to tell yourself that every sport has injuries and gymnastics is no different. Another is to argue that AGG is unique because the body isn't meant to flex and extend as gymnasts do. While there is some truth to those narratives, there are also things that you can do -and things that you can stop doing- to at least decrease the risk of getting injured.

Common sense is not very common, so let's start from the beginning: __If you are recovering from an injury, don't come back too soon__. 
Gymnasts will rush getting back to training while still injured because being young and patient are not synonyms.This sense of urgency will bite you in the back harder than if you would just have waited longer to recover. 

Perhaps you have found yourself in a position where a competition was coming up and you or one of the gymnasts you coach wasn't fully ready. However, you decided to go ahead and step on the carpet. This is typically a terrible choice, and you want to think more long-term than that.
Remember that there are many competitions, but gymnasts only have one pair of knees and one lower back. 

If a gymnast is injured, wait patiently. Try replacing her, or if necessary don't compete at all. I don't care how important the competition is: You do not want to be the coach that causes a young athlete serious back problems for the rest of their life or that triggers an early retirement. Nothing is more important than the golden rule of coaching: do no harm.

The second thing you can do is realize is that __high-level gymnastics is not for everyone__. Gymnasts come in all shapes and sizes, but the ones that are built for AGG are scarce. The sport demands excellent coordination, supple joints, shallow hip sockets and perfect feet among many other characteristics. And that is only physically: the psychological demands are even harder. You need a competitive mindset, the cognitive ability to learn new movements lightning fast and the will to devote a good chunk of your youth to a sport that few people have heard about outside of your family and friends.

With all these requirements to become a top gymnast, it's no wonder why the lower AGG divisions have dozens of teams, but the competitive teams struggle to recruit girls. No one likes to be injured or in constant pain. By definition, not everyone is built for elite sports, and that's alright. There's a place for everyone in AGG, but there's not a place for everyone at the top.

If you're a coach and you don't have the privilege to coach gymnasts that are built to compete at a high level, don't compete at a high level. If you have been training thoroughly but your spine doesn't tolerate rotation and extension very well, leave it alone. Lack of mobility at the upper back, hips, and ankles will result in low back pain and knee problems. This is real life, and the frog doesn't turn into a prince no matter how much you stretch.

A third thing that you want to consider to reduce injuries is __strength training__.
A review of 25 studies in 2013 that included a total of 26610 athletes concluded that strength training reduced sports injuries to less than one third. That's an astonishing 33% reduction!
Also, in this studies, strength training almost halved overuse injuries. You read that right. Not only is strength training the only intervention that will profoundly reduce your acute injury risk, but it will mitigate chronic injuries to 50%. If that weren't enough, strength training will likely improve key performance indicators like your vertical jump and your postural control. If that doesn't convince you to start strength training, nothing will.

Culturally, gymnastics is often anchored to the idea that lifting weights will get you hurt or that it will make you "bulky." All this is nonsense. A gymnast won't lift weights like a bodybuilder: She will lift weights as an athlete that wants to develop power on the carpet. The two are entirely different goals, and anyone with a minimal understanding of physiology and training will know the difference. 

Perfect technique and adequate progression is a must, and strength training needs to be done at least one to two times a week year-round to produce visible results on the carpet.

Another great benefit of lifting weights is increased bone density. If you don't want to be a fragile gymnast, you need a moderate amount of stress on your skeleton. Jumps are one part of the equation, weightlifting with perfect form is the other.Doing too much of it could be a bad thing, but gymnastics without a base of strength is trouble guaranteed. 

Don't fear the weights: every athlete works hard in the gym, and there is no reason why gymnasts shouldn't. Don’t wait to get seriously hurt to start strength training. 

If you liked the article, share it so others may benefit.

#### References:

1.     Jayanthi, N., Pinkham, C., Dugas, L., Patrick, B., & Labella, C. (2013). Sports specialization in young athletes: evidence-based recommendations. Sports Health, 5(3), 251–7. doi:10.1177/1941738112464626

2.     Lauersen, J. B., Bertelsen, D. M., & Andersen, L. B. (2014). The effectiveness of exercise interventions to prevent sports injuries: a systematic review and meta-analysis of randomised controlled trials. British Journal of Sports Medicine, 48(11), 871–7. doi:10.1136/bjsports-2013-092538

3.     Myer, G. D., Jayanthi, N., DiFiori, J. P., Faigenbaum, A. D., Kiefer, A. W., Logerstedt, D., & Micheli, L. J. (2016). Sports Specialization, Part II: Alternative Solutions to Early Sport Specialization in Youth Athletes. Sports Health, 8(1), 65–73. doi:10.1177/1941738115614811

4.     Piazza, M., Battaglia, C., Fiorilli, G., Innocenti, G., Iuliano, E., Aquino, G., … Di Cagno, A. (2014). Effects of resistance training on jumping performance in pre-adolescent rhythmic gymnasts: a randomized controlled study. Italian Journal of Anatomy and Embryology = Archivio Italiano Di Anatomia Ed Embriologia, 119(1), 10–9. Retrieved from http://www.ncbi.nlm.nih.gov/pubmed/25345071


