---
title: The 3 rules of jumps
author: Sergio Navadijo
date: '2020-01-10'
slug: the-3-rules-of-jumps
categories: []
tags: []
description: ''
---

Imagine that you are a gymnast and you want to improve your vertical jump.

By being in the air longer, you will have enough time to raise your legs, extend your upper back and straighten your feet. You will then be more likely to receive a high score from the judges.

If you ask a number of coaches about how to jump higher, most will say "just do more jumps." 

This method, however, won't get you very far.  How could doing more of the same thing that you've been doing for all these years give you different results?

>"**Insanity is doing the same thing over and over again and expecting different results"
-Albert Einstein.**

Yes, there's a few selected group of gymnasts that are **genetically gifted** with great levers and fast twitch muscles. 

They'll be able to jump high in the air no matter how they train -or despite how they train. 

Even if you belong in this lucky group, you could jump even higher if you train according to **the laws of physics**. 

If you were alert in school, you might be familiar with the following: **Force = mass x acceleration**, and **Power = work/time**.

But don't worry, you don't need to re-learn these formulas, or even understand them. All you need to remember is how to use them practically. The best way to do it is to follow the 3 rules of jumps.  
<br />

## Rule 1: Put more force into the ground

The easiest way to develop this ability is to **train against an external resistance**. 

Even though gymnastics is performed with just your bodyweight, it doesn't mean that you this is always the best way. 

To get stronger, you need to overload your muscles. This is easiest accomplished by using traditional implements like barbells, dumbbells, kettlebells and other tools that you will find in most gyms. 

Many exercises could help you jump higher, but for the sake of this example, let us think of one that you are likely to be familiar with: **the barbell squat**. 

The squat is the most researched and one of one of the most time-efficient exercises in modern history. 

Study after study has shown that under most circumstances **increasing the weight that you can lift in the barbell squat will have a direct transfer to the vertical jump** (up to a point). 

A good number to aim for would be to be able to **squat 1.5 times your body weight.** Most research articles and a few old-school strength coaches swear by squatting 2 times bodyweight, but for a young gymnast, 1.5 times bodyweight is more realistic.

For example, if you weigh 50kg, you should be able to back squat 75kg for at least one repetition with perfect form. 

Notice that if you are untrained - regarding weightlifting- a year or more could be necessary to reach that level of strength.

However, **if you can invest in a professional strength and conditioning coach, you will be able to progress a lot quicker**. 

Look for somebody with experience that has a track record of results with other athletes.  
<br />  

## Rule 2: Put force into the ground quicker

Being strong is not enough, and even if you can apply a lot of force into the ground, you need to put this force into the ground quickly.

The heavy strength training we described in rule 1 will help you but you also need to be doing plyometrics. This is a fancy word for jumps where your joints go through a quick stretch-shortening motion.  

An excellent example of a plyometric jump would be the **drop jump**. 

The drop jump consists on the gymnast stepping onto a box of medium height -20cm to 40cm-, dropping down from it to the floor and rebounding as high as possible in the minimum amount of time possible. 

The key here is the word "time". 

The amount of time where the feet contact the ground before the bounce up needs to be very short -200 milliseconds or less. 

Think of a kangaroo continuously hopping on the ground: when it touches the floor, it does so for a very short amount of time.

There is a multitude of different plyometric jumps that will help you develop this quality, but the drop jump is a great starting point. 

Another great way to develop the ability to put force into the ground quicker is **lifting medium to light loads** as quick as you can. 

Let me take the example of the barbell squat from Rule 1.  Imagine taking the maximal load that you can lift for one repetition -say, 100kg- . 

Put 50% of this load -50kg- on the bar and perform 5 sets of 5 repetitions, trying to move the barbell as quick as possible on the way up and in a controlled manner on the way down. 

Now you are training **"strength-speed"** or **"power."** This lighter -but quicker- type of lifting in combination with plyometrics will train you to apply force fast into the ground in a more specific manner.

You can be very strong, but if you can't use that strength in a short amount of time, it won't help you. Therefore this method is a staple for any gymnast that is trying to develop their vertical jumping ability. 

**It is the combination of the hevy strength training and the light load and plyometrics what will yield results**. 

Don't just do one of them in isolation!  
<br />
  
## Rule 3: Lose extra weight

Imagine 2 gymnasts that can put the same amount of force into the ground, and they can put that force into the ground just as quick -as the examples of rules 1 and 2.

Provided that one gymnast is lighter than the other, **the lighter gymnast will jump higher every single time.**

If you carry excess body fat, that is extra baggage that you have to launch into the air. 

Try jumping with a backpack with 3 or 4 extra kilograms, and you will realize how hard it is. Notice I said body fat, not muscle. **Muscle is useful for force production,** and thus you shouldn't be afraid of it. 

Fat, on the other hand, doesn't have contractile properties. In other words, fat not only doesn't help you jump higher, but **it slows you down** and prevents you from jumping high.

However, it is important to be careful when tackling this subject with young peole. Even though I am a proponent of gymnasts staying lean, I am not a fan of measuring body fat percentages. 

First of all, **most measurement devices are very inaccurate and unreliable.** 

Second, there is the possibility that some girls will turn the measurements into a competition, which is a terrible idea. 

However, if you have access to valid and reliable testing technology and you decide to do it, my recommendation would be for gymnasts to stay in the 14% to 20% body fat range.

If a gymnast is already there, there is no need for taking it further: **the risk of eating disorders is real**, and you don't want to take more chances than necessary.

**If you want to perform like an athlete, you must eat like an athlete.**
Provided that you need to make changes, do it the painful way: **Slowly and with the help of a nutritionist**.

>If you want to perform like an athlete, you must eat like an athlete.

The main mistake that you have to avoid at all costs is losing weight too quickly. Not only will it lead to binge eating, but also puts you at **risk of injury and decreases your performance.** 

While body weight and body fat in AGG seems to be a taboo subject in many places -especially in Finland-, other countries like Russia seem to deal with it more openly, weighing the gymnasts periodically. 

You need to individualize your strategy and find the approach that works for you. 

Some gymnasts and parents only need a small set of principles to follow, while others require a more drastic intervention with daily food logs and more accountability.

Having good eating habits, however, will have positive effects on your health now and in the future.

And definitely on your jumps.

#### References:

1.     Augustsson SR. Maximum Strength in Squats Determines Jumping Height in Young Female Volleyball Players. Open Sports Sci J. 2013;6(1):41-46. doi:10.2174/1875399X01306010041

2.     Chelly MS, Fathloun M, Cherif N, Amar M Ben, Tabka Z, Van Praagh E. Effects of a Back Squat Training Program on Leg Power, Jump, and Sprint Performances in Junior Soccer Players. J Strength Cond Res. 2009;23(8):2241-2249. doi:10.1519/JSC.0b013e3181b86c40

3.     Markovic G. Does plyometric training improve vertical jump height? A meta-analytical review. Br J Sports Med. 2007;41(6):349-55; discussion 355. doi:10.1136/bjsm.2007.035113













