---
title: Athletes first, gymnasts second
author: Sergio Navadijo
date: '2020-03-10'
slug: athletes-first-gymnasts-second
categories: []
tags: []
description: ''
---

You are probably familiar with the idea that that early sports specialization increases the risk of injury. 

Research points out that participating in a variety of sports up until your late teens will make you a better athlete and you will get hurt less.

However, it's a tough recommendation to follow.

The training requirements of a junior gymnast -14 to 16 years old- won't allow enough free days to play other sports. You can't train 5 to 6 times per week in AGG and have any regular participation in another sport.

At least not for a long time without burnout or an injury. 

If you add to this school attendance, homework, and whatever reduced form of social life you can get, you end up with a schedule tighter than most adults. 

AGG is somewhat peculiar in that the performance peak is very early in life: between 16 and 20 years old. 

While athletes from most sports peak between 22 and 28 years old, usually gymnasts are underage when they need to be at the best of their abilities.  
<br />

##Inevitable early specialization

Why do gymnasts specialize so early? 

Two reasons: **flexibility** and **technique mastery.**

Flexibility is a unique characteristic in the sense that it is the physical quality that declines the quickest. 

Coaches need to emphasize flexibility training early in life and maintain it thereafter, or you will likely be too stiff to compete at a high level later on.

The second reason for gymnasts peaking too early is that they need a high level of technique mastery.

You can only achieve technique mastery by training thousands of hours year after year, and if a gymnast doesn't start early in life, she won't accumulate the necessary amount of practice required for mastery. 

Many other sports require that level of technical proficiency too, but in AGG you need to have achieved this technique mastery before the inevitable loss of flexibility mentioned earlier.

These two factors make it difficult for gymnasts to avoid early specialization. 

In a perfect world, every gymnast would have a background in various sports and be proficient and many different movement patterns. This way they would have lower risks of injury than what we find today. 

However, it's not likely to happen.

So if we can't train several sports simultaneously, how can we minimize the detrimental effects of sports specialization?  
<br />

##What you can do

I suggest two things: **movement variety** in warmups and **strength training.**

For gymnasts under 12 years old, movement-based warmups should be done in every training. You want to do **exercises that don't look like gymnastics at all.**

For example, to counter so much bending at the spine, you would want to maintain a stiff core and a neutral lower back. 

Think exercises like palloff presses; unilateral farmer walks, rotational medicine ball throws with good mechanics or just picking things off the floor and putting them down with a straight back.

Other great options include overhead squats, overhead carries, and perfect landing mechanics.

Likewise, instead of only repeating movements until perfection and do as the coach says, we would improvise new movements or have drills that demand creativity, decision making and quick reaction times. 

For example sprints with different starting positions, agility circuits or modified dodgeball games.

You get the picture.

All these warmup ideas can be implemented and rotated weekly or daily to **avoid apathy in training.** Even if you are motivated, you will end up bored to death if the only thing you do is repeated gymnastics skills and choreography.

My other proposed solution is to **start organized strength training between 12 and 14 years old.** 

The first and most important thing a gymnast should learn in strength training is **how to pick up a weight off the floor and put it down with a straight back.** 

It doesn't matter if it's a 20kg weight or a sock. Teach this early. 
Once you get older, bad habits are much harder to get rid off. 

Think about it: Most adults swear that they know how to pick up a weight and know that they should bend their knees and keep a straight back. 

But after having coached hundreds of adults -both athletes and general population- I've realized that **they don't want to do it.** 

No matter how many times anyone explains to them how to do it properly, laziness will rule their posture until they get hurt. 

Teach good habits early because the older you get, the harder it is to change your ways.

Once gymnasts learn how to keep a neutral back, they are ready to learn the technique of the main compound movements.

If your team has a qualified strength coach, learning how to do power cleans, squats and push presses at an early age will prevent injuries and improve power in future years. 

During the first two years, the focus should be exclusively on technique. Use tools like bodyweight dumbbells, kettlebells, bands, barbells, and pulleys.

If you are really committed, you can buy your equipment as I did. But if you have no budget, go to the closest gym with your team: in most big cities you can find one literally in every corner. 

If you want to make gymnasts less fragile and stay healthier, strength training needs to be a part of your training program.

Gymnasts may not have time to play different sports. But you can provide enough movement variety in our training warmups and teach basic strength training.