---
title: 3 Things you need to get results
author: Sergio Navadijo
date: '2020-07-11'
slug: 3-things-you-need-to-get-results
categories: []
tags: []
description: ''
---

There are non-negotiable things if you want to get strong and powerful for gymnastics. 

Without these three fundamental pillars, nothing that you do in the gym will improve your performance. Nothing. 

The good news is that these three principles are simple and achievable for anybody. They are universal, don't require money or talent, and you can put them into practice right now. Here are the three principles you need to have:

**1. Patience** when waiting for dynamic correspondence.  
Dynamic correspondence is the transfer of "gym strength" to "AGG Strength." In other words, you can be getting stronger in the gym, but it takes time to see results on the carpet. The first strength gains when you start strength training are fast, but until you see a difference in your jumps, lifts, and posture, you need patience. 

Some gymnasts only need three to six months to see results, while others require a year or two. Gymnasts that don't like to strength train are typically the weaker ones, and thus need it the most. If you are in this group, you are not the only one. For you, hitting the gym can be one of the most annoying things to do. But it needs to be done! Nothing good comes easy.

If it took you ten years or more to become a competent gymnast, use some of that patience in the gym, and you will be a much better gymnast and athlete. It will be worth it. 

**2. Consistency** with showing up and giving your best effort.  
I have seen gymnasts miss every other training and think it's ok. It's not ok! You can't get better by not showing up. Unless you are very injured or very sick, you have to come to training. A gymnast needs to be consistent in every area. 

If you only have strength training in your program once or twice a week, you don't have the luxury of skipping sessions. You need to put your maximum effort into every repetition, not just show up and half-ass the workout. 

Day after day, you need to be comfortable being uncomfortable, always looking to get 1% better. A tiny improvement every week amounts to a lot after a year. It's cliche, but it is true: hard work beats talent when talent doesn't work hard. 

**3. Self-awareness** when feeling pain and having the ability to communicate with your coach.  
There is "good pain" and "bad pain." Good pain is when your muscles hurt from trying very hard. This type of pain is just a side effect of training that won't usually have consequences. Bad pain is when your lower back is sore from gymnastics, and your back isn't ready to strength train in the gym. The latter is the type of pain that should concern you.

The difference between the two seems obvious, but you wouldn't believe how many gymnasts are afraid of saying, "I am not having a good back day." Some would preferably do an exercise in excruciating pain than tell the coach that there is something wrong. 

Every training, the first question should be "how are you doing today?" or "how are you feeling from 1 to 10?". After some time, gymnasts get more in touch with their bodies and learn to recognize when they are in pain. 

The relationship and trust between gymnasts and coaches have to become a priority if you don't want to aggravate chronic injuries.  There are a ton of injuries in gymnastics, and the gym is a place to get stronger, not a place to get more hurt. 